### ISSUE TITLE
diary misses identifying G1 in log fragments

### ISSUE THREAD

**Issue by kirk-microsoft** [microsoft/gctoolkit#106]
During the refactoring something happened that the diary lost the ability to recognize G1 in log fragments.

**Comment by brunoborges** [comment]
Is this an issue that only exists in the PR #107 or is this a problem that exists in the main branch or released version?

If the former, I believe we should discuss a better process. See #109 

If the later, it would be good to have proper build logs failing, links to source code, etc.
