### ISSUE TITLE
mvn test fails

### ISSUE THREAD

**Issue by kittylyst** [microsoft/gctoolkit#11]
Not sure if you're fully released yet, but mvn test currently fails:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (download-test-logs) on project gctoolkit: Unable to find/resolve artifact.: Failed to read artifact descriptor for com.microsoft.gctoolkit:gctoolkit-gclogs:zip:1.0.1: Could not transfer artifact com.microsoft.gctoolkit:gctoolkit-gclogs:pom:1.0.1 from/to github (https://maven.pkg.github.com/microsoft/*): authentication failed for https://maven.pkg.github.com/microsoft/*/com/microsoft/gctoolkit/gctoolkit-gclogs/1.0.1/gctoolkit-gclogs-1.0.1.pom, status: 401 Unauthorized -> [Help 1]

**Comment by dsgrieve** [comment]
Hi Ben. This is a known problem which I thought was addressed in the README, but now I see that slipped through the cracks. The work-around is to clone microsoft/gctoolkit-testdata and do a 'mvn install' so the build will pick up the local repository.

**Comment by karianna** [comment]
> Hi Ben. This is a known problem which I thought was addressed in the README, but now I see that slipped through the cracks. The work-around is to clone microsoft/gctoolkit-testdata and do a 'mvn install' so the build will pick up the local repository.

I thought with a GH PAT folks could get that from GH packages?

**Comment by kittylyst** [comment]
@dsgrieve Doesn't look like that works :(

[beevans@beevans gctoolkit-testdata]$ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.microsoft.gctoolkit:gctoolkit-testdata >-------------
[INFO] Building GCToolKit Test Data 1.0.1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ gctoolkit-testdata ---
[INFO] Installing /home/beevans/projects/gctoolkit-testdata/pom.xml to /home/beevans/.m2/repository/com/microsoft/gctoolkit/gctoolkit-testdata/1.0.1/gctoolkit-testdata-1.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.822 s
[INFO] Finished at: 2021-08-05T18:18:55+02:00
[INFO] ------------------------------------------------------------------------
[beevans@beevans gctoolkit-testdata]$ cd ../gctoolkit
[beevans@beevans gctoolkit]$ mvn test
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] GCToolKit                                                          [pom]
[INFO] core                                                               [pom]
[INFO] api                                                                [jar]
[INFO] parser                                                             [jar]
[INFO] vertx                                                              [jar]
[INFO] sample                                                             [jar]
[INFO] 
[INFO] -----------------< com.microsoft.gctoolkit:gctoolkit >------------------
[INFO] Building GCToolKit 2.0.1-SNAPSHOT                                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:unpack (download-test-logs) @ gctoolkit ---
[INFO] Configured Artifact: com.microsoft.gctoolkit:gctoolkit-gclogs:1.0.1:zip
Downloading from github: https://maven.pkg.github.com/microsoft/*/com/microsoft/gctoolkit/gctoolkit-gclogs/1.0.1/gctoolkit-gclogs-1.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GCToolKit 2.0.1-SNAPSHOT:
[INFO] 
[INFO] GCToolKit .......................................... FAILURE [  2.998 s]
[INFO] core ............................................... SKIPPED
[INFO] api ................................................ SKIPPED
[INFO] parser ............................................. SKIPPED
[INFO] vertx .............................................. SKIPPED
[INFO] sample ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.267 s
[INFO] Finished at: 2021-08-05T18:19:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (download-test-logs) on project gctoolkit: Unable to find/resolve artifact.: Failed to read artifact descriptor for com.microsoft.gctoolkit:gctoolkit-gclogs:zip:1.0.1: Could not transfer artifact com.microsoft.gctoolkit:gctoolkit-gclogs:pom:1.0.1 from/to github (https://maven.pkg.github.com/microsoft/*): authentication failed for https://maven.pkg.github.com/microsoft/*/com/microsoft/gctoolkit/gctoolkit-gclogs/1.0.1/gctoolkit-gclogs-1.0.1.pom, status: 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by dsgrieve** [comment]
@kittylyst Oh... my apologies. Try `for f in `find . -name pom.xml`; do mvn install --file $f; done`

But maybe you also need the PAT, as @karianna mentions. I'd be interested to know if the PAT works for you. (It works for me, but not for others),

**Comment by kittylyst** [comment]
It gets further than it did, but I now see a test failure:

[INFO] Running com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.317 s <<< FAILURE! - in com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest
[ERROR] com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest.testForDetailsTenuring  Time elapsed: 2.734 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: ps/details/tenuring/p_app_02_gc.log.zip, calculated: false, expected: true ==> expected: <true> but was: <false>
	at gctoolkit.parser.test/com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest.testForDetailsTenuring(ParallelJVMConfigurationTest.java:37)

**Comment by dsgrieve** [comment]
@kittylyst - Works for me, and the github build passes as well. Pay careful attention to https://github.com/microsoft/gctoolkit-testdata/blob/main/README.md and gctoolkit-testdata's dependence on Git Large File Storage (LFS). 

Clearly we need to update the README in gctoolkit....

**Comment by pliakas** [comment]
> Hi Ben. This is a known problem which I thought was addressed in the README, but now I see that slipped through the cracks. The work-around is to clone microsoft/gctoolkit-testdata and do a 'mvn install' so the build will pick up the local repository.

Hello, 
 it seems that "mvn install" is not working in the main  (root) project of microsoft/gctoolkit-testdata. You need to build each maven module individually. 

I have created a quick script that can be used in the root project of gctoolkit-testdata. 

> #!/bin/bash
> 
> echo "Builing module :: main"
> mvn clean install
> 
> echo "Building module :: 'gctoolkit-gclogs'"
> cd gctoolkit-gclogs && mvn clean install && cd ..
> 
> 
> echo "Building 'gctoolkit-gclogs-rolling"
> cd gctoolkit-gclogs-rolling && mvn clean install & cd ..
> 
> echo "Building module :: gctoolkit-shenandoah-logs"
> cd gctoolkit-shenandoah-logs && mvn clean install && cd ..
> 
> echo "Buidling module :: gctoolkit-zgc-logs"
> cd gctoolkit-zgc-logs && mvn clean install && cd ..

**Comment by SubOptimal** [comment]
In the pom of `gctoolkit-testdata`, the separate `gctoolkit-*` are added as dependency and not as a Maven module. Hence they need to be processed individually.

see: https://github.com/microsoft/gctoolkit-testdata/blob/main/pom.xml#L68

```
    <!--                                                                                                                                                                                      
    <modules>                                                                                                                                                                                 
        <module>gctoolkit-gclogs</module>                                                                                                                                                     
        <module>gctoolkit-gclogs-rolling</module>                                                                                                                                             
        <module>gctoolkit-zgc-logs</module>                                                                                                                                                   
    </modules>                                                                                                                                                                                
    -->                                                                                                                                                                                       
```

**Comment by brunoborges** [comment]
I'd suggest adding gctoolkit-testdata as a submodule of the main gctoolkit project. This way, the content is separate in terms of Git repo ('cause testdata has a lot of files), but it then becomes easier from end user perspective to pull the content and build. As in, add a shell script into core that does these git/build steps.

**Comment by dsgrieve** [comment]
@SubOptimal - Commenting out the modules was done so that the top-level pom could include dependencies on the individual modules (beginning on line 76 of the referenced pom file). The idea was to allow each set of log files be versioned independently of the other. That way, one could add, say, ZGC logs and we wouldn't have to repackage and download all the other logs. It made sense (to me) at the time.

**Comment by dsgrieve** [comment]
https://github.com/microsoft/gctoolkit-testdata/pull/2 to fix `mvn install`

**Comment by dsgrieve** [comment]
Gave better documentation for the need to authenticate with github packages. 
https://github.com/microsoft/gctoolkit/commit/fd80c761bd5e88f06e8e21e4f96d92569d9e68f0
