### ISSUE TITLE
Adding Test Coverage Report, Static Code Analysis & Code Style Check

### ISSUE THREAD

**Issue by pliakas** [microsoft/gctoolkit#14]
I would recommend to add the following tools 

### Test Coverage
>  I would be useful to add JaCoCo in order to have a test coverage report and in the future set the limits for test coverage. It can be also enabled in the build pipelines. 

### Static code Analysis
> Maybe also some static code analysis tool, such as [Spotbugs](https://spotbugs.github.io.)

### Code style
> Adding also support to [Checkstyle](https://checkstyle.org) based on predefined code style

**Comment by karianna** [comment]
Agreed, I think we'd prefer this to be Maven based reporting, see #8

**Comment by anantk24** [comment]
I would recommend using sonar cloud  for static code analysis. 
On Spotbugs [website ](https://spotbugs.readthedocs.io/en/stable/introduction.html) suggest "SpotBugs can scan bytecode (class files) generated by JDK8 and newer versions. However, support for Java 11 and newer is still experimental. Visit issue tracker to find known problems." 
Above project has started working on JDK 11.
Any comments?

**Comment by karianna** [comment]
We typically use checkstyle, PMD, and Spotbugs on projects.  Sonar cloud is often OTT, but I'd be curious to explore it if we can use a free tier.

**Comment by anantk24** [comment]
As sonarcloud is [free](https://sonarcloud.io/pricing) for public projects, can be explored for this project. Only thing is maintainer has to setup GitHub workflow for sonar cloud. Checkstyle, PMD spotbugs can be configured in maven . 


I would be happy to  take up this task, once everything is finalized.

**Comment by karianna** [comment]
> As sonarcloud is [free](https://sonarcloud.io/pricing) for public projects, can be explored for this project. Only thing is maintainer has to setup GitHub workflow for sonar cloud. Checkstyle, PMD spotbugs can be configured in maven .
> 
> I would be happy to take up this task, once everything is finalized.

OK so Microsoft is an org in Sonarcloud but we need to get the core committers added before we can set that up.  In the meantime, if you'd like to add Checkstyle, PMD, and Spotbugs to our Maven reporting that would be most welcome!

**Comment by anantk24** [comment]
Sure. I will take it up. Please assign it to me.

**Comment by pliakas** [comment]
@karianna @anantk24 i already started with the Jacoco, but you can do the other :) no problem :)

**Comment by anantk24** [comment]
I think this issue has been fixed. Spotbugs and checkstyle related changes are merged .
@pliakas has merged changes related jacoco.
@pliakas Can we close this issue?

**Comment by kirk-microsoft** [comment]
done
