### ISSUE TITLE
Upgrade vert.x dependencies to 4.1.5

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#140]
vert.x 4.1.2 pulls in netty 4.1.65.final which has a DOS security vulnerability. The code involved is never executed by gctoolkit, but this does cause issues for dependency verification. vert.x 4.1.5 depends on netty 4.1.68.final which does not have the vulnerability.

After this upgrade, a new release of gctoolkit should be created.

References:
https://github.com/netty/netty/blob/netty-4.1.67.Final/codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameDecoder.java#L79
https://github.com/netty/netty/blob/netty-4.1.67.Final/codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameDecoder.java#L171
https://github.com/netty/netty/blob/netty-4.1.67.Final/codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameDecoder.java#L185

**Comment by brunoborges** [comment]
@karianna I think there might be a bit of confusion with the template SECURITY.md and our case here. To my understanding - which *may be wrong! - SECURITY.md is for security flaws within the software we Microsoft write ourselves entirely.
