### ISSUE TITLE
Extract command line from PreUnifiedJVMConfiguration log file

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#149]
https://github.com/microsoft/gctoolkit/blob/6f0b5852f862b1380a284c388104870efe103196/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/PreUnifiedJVMConfiguration.java#L123

**Comment by kirk-microsoft** [comment]
Command line is extracted for preunified logs
