### ISSUE TITLE
Understand why -1.0d as the default?

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#150]
https://github.com/microsoft/gctoolkit/blob/8d88dfc64891b1a877ddaeeab104d9e94119e6f4/parser/src/main/java/com/microsoft/gctoolkit/parser/JHiccupTrace.java#L22

**Comment by kirk-microsoft** [comment]
these numbers should never be negative and if they are then they've never been set. This is used in cases where data may, or may not show up.. or we want to set the value once and once only

**Comment by karianna** [comment]
@kirk-microsoft - did you replace the comment in the code with your explanation?

**Comment by kirk-microsoft** [comment]
Adding comments to the code is an ongoing group effort that is being addressed in each additional pull request.
