### ISSUE TITLE
Implement Concurrent Mode Failures in GenerationalHeapParser

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#153]
https://github.com/microsoft/gctoolkit/blob/4852eb3d1388fe4dc9de8e115fad28bb3581796e/parser/src/main/java/com/microsoft/gctoolkit/parser/GenerationalHeapParser.java#L1459

**Comment by kirk-microsoft** [comment]
ConcurrentModeFailures are managed in a separate parser
