### ISSUE TITLE
JVMEventParser: smart checker for concatenated logs

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#154]
https://github.com/microsoft/gctoolkit/blob/4852eb3d1388fe4dc9de8e115fad28bb3581796e/parser/src/main/java/com/microsoft/gctoolkit/parser/JVMEventParser.java#L77

**Comment by kcpeppe** [comment]
JVMEventParser has no awareness of the DataSource. If the DS closes or otherwise terminates, a termination event is published
