### ISSUE TITLE
Having an issue with building the solution

### ISSUE THREAD

**Issue by MichaelJCook** [microsoft/gctoolkit#179]
Getting an error when building GCToolkit.  Could you please help me understand what I can try to do to get maven working?

Thank you.

These are the steps I took:

Downloaded Docker build from here:

https://hub.docker.com/_/ubuntu

Command: "docker pull ubuntu"

CLI in docker -

Command:  "cd /"

Command: "git clone https://github.com/microsoft/gctoolkit.git"

Download maven 3.8.4

Command: "wget https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz"
Command: "mkdir /maven"
Command: "mv /https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz /maven"
Command: "tar -xzvf https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz"

Command: "export M2_HOME=/maven/apache-maven-3.8.4"
Command: "export M2=$M2_HOME/bin"
Command: "export MAVEN_OPTS="-Xms256m -Xmx512m""
Command: "export PATH=$M2:$PATH"

Then I set up the mvnw wrapper in gctoolkit dir

Command: "cd /gctoolkit"

Command: "mvn -N io.takari:maven:wrapper -Dmaven=3.8.4"

I check to ensure we're running the right version:

Command: "./mvnw -version"

Output:
root@124e026f7dfb:/gctoolkit#  ./mvnw -version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /root/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.10.76-linuxkit", arch: "amd64", family: "unix"

I then try to clean and compile:

Command: "./mvnw clean compile"

All Successful clean and compile

I get an error when executing:
Command: " ./mvnw exec:exec"

root@124e026f7dfb:/gctoolkit# ./mvnw exec:exec
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 6 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 6 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] GCToolKit                                                          [pom]
[INFO] GCToolKit GCLogs                                                   [pom]
[INFO] GCToolKit API                                                      [jar]
[INFO] GCToolKit Parser                                                   [jar]
[INFO] GCToolKit Vertx                                                    [jar]
[INFO] GCToolKit Sample                                                   [jar]
[INFO] 
[INFO] -----------------< com.microsoft.gctoolkit:gctoolkit >------------------
[INFO] Building GCToolKit 2.0.5-SNAPSHOT                                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ gctoolkit ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GCToolKit 2.0.5-SNAPSHOT:
[INFO] 
[INFO] GCToolKit .......................................... FAILURE [  0.287 s]
[INFO] GCToolKit GCLogs ................................... SKIPPED
[INFO] GCToolKit API ...................................... SKIPPED
[INFO] GCToolKit Parser ................................... SKIPPED
[INFO] GCToolKit Vertx .................................... SKIPPED
[INFO] GCToolKit Sample ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.237 s
[INFO] Finished at: 2021-12-06T11:51:13-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project gctoolkit: The parameter 'executable' is missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by brunoborges** [comment]
Hi @MichaelJCook,

I just ran a build again and it is all working fine: https://github.com/microsoft/gctoolkit/actions/runs/1546069872

Any chance you can review our [CONTRIBUTING](https://github.com/microsoft/gctoolkit/blob/main/CONTRIBUTING.md#build) guide?

**Comment by MichaelJCook** [comment]
Thanks.  Had not run "mvn package".  All working now.
