### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by MichaelJCook** [microsoft/gctoolkit#182]
I can run the gctoolkit from maven, using the mvnw exec:exec command.

I would like some help with problem I am having running the Main from the command line directly.  I've pasted the console output below.  The Main runs, but there is no output when run directly.  

Could you please advise a way for me to run the sample from a command prompt without maven?

Thank you,
Mike

mike@124e026f7dfb:~/gctoolkit/sample$ ../mvnw exec:exec
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] --------------< com.microsoft.gctoolkit:gctoolkit-sample >--------------
[INFO] Building GCToolKit Sample 2.0.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ gctoolkit-sample ---
Dec 09, 2021 10:10:34 AM io.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
The XYDataSet for Remark contains 26 items.
The XYDataSet for InitialMark contains 26 items.
The XYDataSet for DefNew contains 19114 items.
Total pause time  : 208.9224
Total run time    : 608797.8946
Percent pause time: 0.03
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.865 s
[INFO] Finished at: 2021-12-09T10:10:39-05:00
[INFO] ------------------------------------------------------------------------

mike@124e026f7dfb:~/gctoolkit/sample$ cd -
/home/mike/gctoolkit/sample/target/classes

mike@124e026f7dfb:~/gctoolkit/sample/target/classes$ java -cp $CP -DgcLogFile=../../../gclogs/preunified/cms/defnew/details/defnew.log  com.microsoft.gctoolkit.sample.Main

mike@124e026f7dfb:~/gctoolkit/sample/target/classes$ echo $CP

/home/mike/gctoolkit/sample/netty-all-4.1.36.Final.jar:/home/mike/gctoolkit/sample/netty-all-4.0.0.final.jar:/home/mike/gctoolkit//api/target/classes/:/home/mike/gctoolkit/vertx/target/classes/:/home/mike/gctoolkit/parser/target/classes/:/home/mike/gctoolkit//api/target/classes/com/microsoft/gctoolkit/io/:/home/mike/gctoolkit/sample/netty-all-4.1.70.Final.jar::/home/mike/gctoolkit/sample/vertx-core-4.2.1.jar:

**Comment by dsgrieve** [comment]
The easiest thing to do is to throw a --debug on the mvn command line. The debug output will show you exactly what mvn is exec'ing.

**Comment by dsgrieve** [comment]
Interesting that your debug output looks different from mine. It looks like it's running a unit test, not a java command line. 

Anyway... I pieced this together from my output. This is on a Mac. YMMV. 

After running `./mvnw install`

```
java --module-path $HOME/gctoolkit/sample/target/classes:$HOME/.m2/repository/com/microsoft/gctoolkit/gctoolkit-api/2.0.5-SNAPSHOT/gctoolkit-api-2.0.5-SNAPSHOT.jar:$HOME/.m2/repository/com/microsoft/gctoolkit/gctoolkit-vertx/2.0.5-SNAPSHOT/gctoolkit-vertx-2.0.5-SNAPSHOT.jar:$HOME/.m2/repository/com/microsoft/gctoolkit/gctoolkit-parser/2.0.5-SNAPSHOT/gctoolkit-parser-2.0.5-SNAPSHOT.jar:$HOME/.m2/repository/io/vertx/vertx-core/4.1.5/vertx-core-4.1.5.jar:$HOME/.m2/repository/io/netty/netty-common/4.1.68.Final/netty-common-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-buffer/4.1.68.Final/netty-buffer-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-transport/4.1.68.Final/netty-transport-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-handler/4.1.68.Final/netty-handler-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-codec/4.1.68.Final/netty-codec-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-handler-proxy/4.1.68.Final/netty-handler-proxy-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-codec-socks/4.1.68.Final/netty-codec-socks-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-codec-http/4.1.68.Final/netty-codec-http-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-codec-http2/4.1.68.Final/netty-codec-http2-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-resolver/4.1.68.Final/netty-resolver-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-resolver-dns/4.1.68.Final/netty-resolver-dns-4.1.68.Final.jar:$HOME/.m2/repository/io/netty/netty-codec-dns/4.1.68.Final/netty-codec-dns-4.1.68.Final.jar:$HOME/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar --module com.microsoft.gctoolkit.sample/com.microsoft.gctoolkit.sample.Main gclogs/preunified/cms/defnew/details/defnew.log
```

**Comment by MichaelJCook** [comment]
Thanks, David.  That's very helpful!

I have it working now.
