### ISSUE TITLE
@Aggregates({EventSource.SAFEPOINT}) will fall into dead loop

### ISSUE THREAD

**Issue by ZhangShushu123** [microsoft/gctoolkit#183]
When I create an Aggregator with @Aggregates({EventSource.SAFEPOINT}). The program will loop forever.
I read the source code and I found that there is no LogFileParser with the outbox _SAFEPOINT_ . 
Therefore, when the program execute the code `aggregatorVerticles.forEach(AggregatorVerticle::awaitCompletion);` , the Aggregator with @Aggregates({EventSource.SAFEPOINT}) will not complete forever.

**Comment by ZhangShushu123** [comment]
Is GCToolkitVertxParametersForPreUnifiedLogs.java line 140 `AggregatorVerticle aggregatorVerticle = new AggregatorVerticle(SAFEPOINT_OUTBOX);` change to `AggregatorVerticle aggregatorVerticle = new AggregatorVerticle(GCToolkitVertx.JVM_EVENT_PARSER_OUTBOX);`? 
Because there is no AggregatorVerticle with the inbox _JVM_EVENT_. 
However, I think we should add an `EventSource` enum value of _JVM_EVENT_ will be better than the before one.

**Comment by dsgrieve** [comment]
Nice find! 

I think the issue here is that the SafePointParser is never created. I think part of the fix is to add this block of code to the `initLogFileParsers` method of GCToolkitVertxParametersForPreUnifiedLogs. 
```java
        if (diary.isApplicationStoppedTime() || diary.isApplicationRunningTime()) {
            logFileParsers.add(new LogFileParser(GCToolkitVertx.PARSER_INBOX, SAFEPOINT_OUTBOX, consumer -> new SafepointParser(diary, consumer)));
        }
```
The `if (diary.isApplicationStoppedTime() || diary.isApplicationRunningTime())` test is probably needed around the code that calls `getAggregators(EventSource.SAFEPOINT, registeredAggregations)` down in `initAggregatorVerticles` in the same class.

It would be awesome, @ZhangShushu123, if you could work this issue!

**Comment by ZhangShushu123** [comment]
By the way, I think adding code to remove `aggregatorVerticles` which inbox can not match with the `logFileParser `in `aggregateDataSource()` is a better way, because it will prevent the dead loop. Moreover, logging the removed `aggregatorVerticle`  in console with error level will tell us which `aggregatorVerticle` can not match and we should fix in the future.

**Comment by ZhangShushu123** [comment]
The code which should be added in aggregateDataSource() will show below. Of course, the code can be written more gracefully.
```
 aggregatorVerticles.removeIf(aggregatorVerticle -> {
      boolean isMatch = logFileParsers.stream().anyMatch(logFileParser -> logFileParser.getOutbox() == aggregatorVerticle.getInbox());
      if(!isMatch){
            LOGGER.log(Level.SEVERE, String.format("%s %s",aggregatorVerticle.getInbox(),aggregatorVerticle));
      }
      return !isMatch;
});
```

**Comment by dsgrieve** [comment]
@ZhangShushu123 - would you be willing to create a PR for these changes?

**Comment by ZhangShushu123** [comment]
Of course. I will take a pull request as soon as possible.

**Comment by ZhangShushu123** [comment]
Thank you very much for taking the time to merge code. And I look forward to your next refactoring work.
