### ISSUE TITLE
Do we need this impl class? Since this class is essentially a wrapper around Diary, can JvmConfiguration be changed from an interface to a class?

### ISSUE THREAD

**Issue by kirk-microsoft** [microsoft/gctoolkit#184]
Do we need this impl class? Since this class is essentially a wrapper around Diary, can JvmConfiguration be changed from an interface to a class?

_Originally posted by @dsgrieve in https://github.com/microsoft/gctoolkit/pull/173#discussion_r751595081_

I would like to see Impl classes be resolved to a type specific abstraction

**Comment by kcpeppe** [comment]
The impl class has been removed
