### ISSUE TITLE
Release 2.0.6 not in Maven Central

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#208]
There is no release `2.0.6` in Maven Central: https://search.maven.org/artifact/com.microsoft.gctoolkit/gctoolkit

But there is a tag/release for 2.0.6 here: https://github.com/microsoft/gctoolkit/releases/tag/gctoolkit-2.0.6

Was this a problem in our build pipeline, @kcpeppe ?

**Comment by kirk-microsoft** [comment]
my bad, I made a mistake resulting in 2.0.6 got skipped. If there is a point in correcting this then....
