### ISSUE TITLE
Sample project unable to parse G1 GC log files

### ISSUE THREAD

**Issue by massdosage** [microsoft/gctoolkit#209]
**Describe the bug**
I have tried to run the sample project on log files generated by the (default) G1 garbage collector in Java 11. It fails to process these without indicating what is going wrong. Does it perhaps only support a certain format of the Java 11 unified logs?

**To Reproduce**
1. Generate a Java 11 GC log file from your application by using these flags: "-Xlog:gc:file=/tmp/gc.log:tags,uptime,level:filecount=3,filesize=100M" or "-Xlog:gc=info:file="/tmp/gc.log":tags,uptime,level" (I tried two variations to see if there would be any difference but they both result in the same error)
2. From `gctoolkit/sample` run "mvn exec:exec -DgcLogFile=/tmp/gc.log"
3. This is the output I see:
```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] --------------< com.microsoft.gctoolkit:gctoolkit-sample >--------------
[INFO] Building GCToolKit Sample 2.0.8-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ gctoolkit-sample ---
Feb 17, 2022 2:47:53 PM io.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
Total pause time  : 0.0000
Total run time    : 0.0000
Percent pause time: NaN
```
at which point Maven freezes and nothing else happens, I then have to CTRL-C to stop the process.

**Expected behavior**
A summary of the contents of the GC log.

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by kcpeppe** [comment]
Hi, sorry for the delay in writing back. There is a recommended set of flags for G1 unified logging that if not followed I'm sure will result in some grief. If you check the log file I think you'll find the issue there. It's in the roadmap that G1 should more robustly support a lesser set of flags, it's just not something that has bubbled up as of yet.

Recommended flags -> -Xlog:gc*,gc+ref=debug,gc+phases=debug,gc+age=debug,safepoint:file=<xxx>

I would stick to the default set of decorators unless you're in need of date stamps at which time I'd add that decorator to the list. If you leave out uptime with only date time, GCToolKit will use an estimate for uptime.

**Comment by massdosage** [comment]
OK, thank you, that makes sense and quite a few of the Garbage Collection tools document the subset of flags that they support. I tried again with the ones you suggested and it worked (although the Maven VM never exited, not sure if that's intentional and whether it "tails" the file?)

Are these "recommended" flags documented somewhere that I missed? Or should they be added? Maybe to the README for the samples to show what do use when one generates the file?

In future it would be great if one could pass the toolkit the flags that were used and it would then be able to handle pretty much any format as long as it's told what the format is.

**Comment by kcpeppe** [comment]
The intent has always been to increase the number of supported flag combinations. In JDK approximately 3.0 different flag combinations have been tested. For UL, the focus was on a minimal set that produced all the data that is likely necessary to tune while unintentionally ignoring those that seemed relevant only to VM engineers

**Comment by kcpeppe** [comment]
I should add, the other approach is to adjust GC UL levels. For example, age table data yields a very useful view of overt transient activity. This is of course, essential information in the tuning to reduce GC cycles in tenured. This information should be printed at the default info level IMHO. This would simplify the command line a wee bit.
