### ISSUE TITLE
Update README to make Hotspot support clearer 

### ISSUE THREAD

**Issue by karianna** [microsoft/gctoolkit#21]
Hi everyone!

Thanks for sharing such a great tool! I would love to try it, but it seems that it is only compatible with HotSpot JVMs.
Consider this sentence from your README:

> GCToolKit is a set of libraries for analyzing Java garbage collection (GC) log files

It should probably be:

> GCToolKit is a set of libraries for analyzing **_Hotspot_** Java garbage collection (GC) log files

I know MS' JVM is yet another hotspot distribution like 99% of the other JVMs out there, but [OpenJ9](https://www.eclipse.org/openj9/) does have a significant use case and is typically used in conjunction with [OpenLiberty](https://github.com/OpenLiberty/open-liberty).

Many thanks,
\- Ben

_Originally posted by @bmarwell in https://github.com/microsoft/gctoolkit/discussions/20_

**Comment by anantk24** [comment]
Hi @karianna ,
I would like to take this issue.  Can you assign it to me?

**Comment by anantk24** [comment]
Added [pull request](https://github.com/microsoft/gctoolkit/pull/23) . Kindly review and would be happy to work on comments.

**Comment by dsgrieve** [comment]
commit 4a87ddf
