### ISSUE TITLE
G1GC Archive regions

### ISSUE THREAD

**Issue by kcpeppe** [microsoft/gctoolkit#211]
GCToolkit recognized but does not use the data to account for G1 archive regions when calculating the size and occupancy of tenured.

GCToolkit's calculation of tenured should subtract archive regions from the tenured total.

**Comment by kkdlau** [comment]
I would love to work on this issue! Could you please point me to the specific file(s) that would need to be modified for this issue?

**Comment by karianna** [comment]
@kcpeppe for guidance :-)

**Comment by kkdlau** [comment]
@kcpeppe appreciate if you could provide guidance

**Comment by dsgrieve** [comment]
@kkdlau - G1GCPauseEvent#getTenured()

**Comment by dsgrieve** [comment]
Thanks, @kkdlau, for your contribution and for you patience with us!
