### ISSUE TITLE
GCToolkitVertxParameters#createAggregator should not arbitrarily pick the first constructor

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#214]
**Describe the bug**
com.microsoft.gctoolkit.vertx.jvm.GCToolkitVertxParameters#createAggregator does this:
`            return (Aggregator<?>) aggregatorClass.getConstructors()[0].newInstance(aggregationClass.getConstructors()[0].newInstance());
`
But this could blow up if the class has more than one constructor. Instead, the code should look for the no-arg constructor (for the Aggregation) and the constructor that takes an Aggregation (for the Aggregator).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brunoborges** [comment]
Any thoughts on doing a builder interface/factory?

**Comment by kcpeppe** [comment]
Fix is easy, filter through the list and look for the zero agr constructor.
can you suggest how a builder or factory anti-pattern helps?

**Comment by dsgrieve** [comment]
https://github.com/microsoft/gctoolkit/pull/216
