### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [microsoft/gctoolkit#217]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `gctoolkit-vertx\pom.xml`, `io.vertx:vertx-core` scope should be `provided`  instead of `compile`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by dsgrieve** [comment]
I would agree if gctoolkit was a reactive app, but it is not. gctoolkit make use of the verx-core message bus, but not much else. Therefore, it is not reasonable to expect the runtime environment to provide the lib.
