### ISSUE TITLE
[INFO] Running com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest

### ISSUE THREAD

**Issue by karianna** [microsoft/gctoolkit#222]
[INFO] Running com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest
[ERROR] com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.unifiedLog  Time elapsed: 0.037 s  <<< ERROR!
java.lang.RuntimeException: unified/g1gc/gc-all-info.log.zip not found
	at com.microsoft.gctoolkit.integration@2.0.11-SNAPSHOT/com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.logTest(SingleGarbageCollectionLogFileTest.java:22)
	at com.microsoft.gctoolkit.integration@2.0.11-SNAPSHOT/com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.unifiedLog(SingleGarbageCollectionLogFileTest.java:61)

_Originally posted by @karianna in https://github.com/microsoft/gctoolkit/issues/221#issuecomment-1176624983_

**Comment by dsgrieve** [comment]
Test file is missing, but @kcpeppe should have it. I'll disable the test until the file can be uploaded.

**Comment by dsgrieve** [comment]
@kcpeppe FYI: I commented out the missing file from the list of files in the test so you'll need to undo my hack once the `unified/g1gc/gc-all-info.log.zip` has been uploaded. 
```
diff --git a/IT/src/test/java/com/microsoft/gctoolkit/integration/io/SingleGarbageCollectionLogFileTest.java b/IT/src/test/java/com/microsoft/gctoolkit/integration/io/SingleGarbageCollectionLogFileTest.java
index c79f244..e2e760e 100644
--- a/IT/src/test/java/com/microsoft/gctoolkit/integration/io/SingleGarbageCollectionLogFileTest.java
+++ b/IT/src/test/java/com/microsoft/gctoolkit/integration/io/SingleGarbageCollectionLogFileTest.java
@@ -15,7 +15,7 @@ import static org.junit.jupiter.api.Assertions.*;
 public class SingleGarbageCollectionLogFileTest {
 
 
-    private String[] unifiedLogs = { "unified/cms/gc.log", "unified/g1gc/G1-80-16gbps2.log.0", "unified/g1gc/gc-all-info.log.zip"};
+    private String[] unifiedLogs = { "unified/cms/gc.log", "unified/g1gc/G1-80-16gbps2.log.0"/*, "unified/g1gc/gc-all-info.log.zip"*/};
     private boolean[] zipped = { false, false, true};
 
     private void logTest(String log, boolean zipped) {
```
