### ISSUE TITLE
Add messaging API to api module

### ISSUE THREAD

**Issue by karianna** [microsoft/gctoolkit#237]
Current implementation has a circular dependency because we are too tightly coupled to vert.x.  Adding this API will break the code coupling which can lead to a further refactoring.

This is important before we add new features like GenShen and GenZGC parsing.

https://github.com/microsoft/gctoolkit/issues/237#tasklist-block-37859257-88f0-46f4-9886-0fc62a30d37e

**Comment by karianna** [comment]
Messaging API has been settled upon. Parser and Analytics need to be rewired in and then the tests updated.

**Comment by dsgrieve** [comment]
Duplicate of issue #4

**Comment by karianna** [comment]
#252
