### ISSUE TITLE
Are there any docs for this project?

### ISSUE THREAD

**Issue by mikehearn** [microsoft/gctoolkit#24]
Showing what analyses it can do, what it outputs, how to run it etc?

**Comment by karianna** [comment]
The `README.md` at the root of the project should be your starting point and a https://github.com/microsoft/gctoolkit/tree/main/sample sample project.  But I feel there is a Ux bug here!

**Comment by v-sreekesh** [comment]
Hi @karianna I would like to help with this UX bug you have mentioned could you link me to detailed blog post ?

**Comment by mikehearn** [comment]
I read the README before filing this issue of course. I wouldn't quite call that documentation. It tells you more about how to contribute than about what the tool actually does.

**Comment by karianna** [comment]
> Hi @karianna I would like to help with this UX bug you have mentioned could you link me to the detailed blog post?

The UX bug I'm referring to is the lack of documentation (and links!) in the `README.md` file :-).  I think that's one the original authors are going to have to rectify.

**Comment by karianna** [comment]
> I read the README before filing this issue of course. I wouldn't quite call that documentation. It tells you more about how to contribute than about what the tool actually does.

Agreed, I've updated the issue and we'll get onto this!

**Comment by karianna** [comment]
We think #27 resolves this.  More feedback welcome!
