### ISSUE TITLE
Question: periodic analyse active gclog

### ISSUE THREAD

**Issue by loyispa** [microsoft/gctoolkit#242]
**Is your feature request related to a problem? Please describe.**
Thanks for providing such excellent works. Currently I want to periodically analyze active gc logs per minute，is this supported at present？

**Comment by karianna** [comment]
@loyispa I assume you're looking to stream the log into GCtoolkit and re-analyze, so something like GCToolkit as a service?

**Comment by loyispa** [comment]
> @loyispa I assume you're looking to stream the log into GCtoolkit and re-analyze, so something like GCToolkit as a service?

That's it！

**Comment by karianna** [comment]
Unfortunately that's out of scope for GCToolkit itself (that would have to be a separate project of some description I feel)
