### ISSUE TITLE
GCToolKit deadlocks

### ISSUE THREAD

**Issue by kcpeppe** [microsoft/gctoolkit#265]
**Describe the bug**
GCToolKit hangs when no aggregations have passed.

Start GCToolKit with no Aggregation for the module SPI to find.

**Expected behavior**
GCToolKit should not process a log when there are no Aggregations registered.
GCToolKit should allow for Aggregation to be logged as they are registered.

** Action **
Add a test for this case.

**Comment by kcpeppe** [comment]
I think that is what is happening in this case.

**Comment by kirk-microsoft** [comment]
Solved in PR #266
