### ISSUE TITLE
Testing of GCToolKit without modules

### ISSUE THREAD

**Issue by kirk-microsoft** [microsoft/gctoolkit#268]
The NoModuleIntegrationTest in the IT maven module is currently disabled. It is designed to run an end-to-end smoke test of using GCToolKit on the classpath instead of on the module-path. Currently the test runs locally but in the maven build it is run within the module system which fails as the test directly references classes in the vertx module that are not exported. This reference is *only* for the purposes of the test.

The ask is for finding a solution that would allow for the test to be turned on. The test does make use of JUnit5 @Tag annotations so it likely that a maven profile will suffice. That said, any better solution is also welcomed.

**Comment by dsgrieve** [comment]
@kirk-microsoft @kcpeppe I believe you may have forgotten to add NoModuleIntegrationTest.java

**Comment by kirk-microsoft** [comment]
@dsgrieve it is there in the IT test folder in the phaser branch. At issue is, I rebased phaser against main a few hours ago, no one has committed anything since then and my local branch of phaser is now 1 commit behind main???? Unbelievable!

**Comment by kirk-microsoft** [comment]
Sorry about that... I was thinking I should have put the complete path in but... got lazy... my bad!

**Comment by kirk-microsoft** [comment]
solution found and implemented
