### ISSUE TITLE
Don't need of additional stream.

### ISSUE THREAD

**Issue by logesh056** [microsoft/gctoolkit#298]
In UnifiedG1GCParser class the methods publishConcurrentEvent and publishUndoCycle have queue iterating. In that queue iterating the stream is not necessary. It makes overhead in that place only. Can you remove that and make some optimization?
 
`private void publishConcurrentEvent(G1GCConcurrentEvent event) {
        if ( event == null) return;

        if ( forwardReference.getGcType() != GarbageCollectionTypes.G1GCConcurrentUndoCycle) {
            publish(event);
            concurrentPhaseActive = false;
            eventQueue.stream().forEach(this::publish);
            eventQueue.clear();
        } else {
            eventQueue.add(event);
        }
    }

    private void publishUndoCycle(G1ConcurrentUndoCycle cycle) {
        concurrentPhaseActive = false;
        publish(cycle);
        eventQueue.stream().forEach(this::publish);
        eventQueue.clear();
    }`

or can use parallel stream it makes benefits?

**Comment by kcpeppe** [comment]
The aggregations are expecting events to arrive in time order of when they started. The queuing ensures this time-ordering.

**Comment by dsgrieve** [comment]
Iterating over the stream is indeed necessary. The model is that events are published in the order they were logged to the GC log file. Existing uses of the toolkit depend on that ordering. Using a parallel stream would mean the events could be published in any order, which would break existing uses.
