### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (download-test-logs) on project gctoolkit: Unable to find/resolve artifact.

### ISSUE THREAD

**Issue by andotorg** [microsoft/gctoolkit#30]
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (download-test-logs) on project gctoolkit: Unable to find/resolve artifact.

**Comment by karianna** [comment]
@andotorg can you run that again with `mvn -X <command>` and post the relevant output here?

**Comment by dsgrieve** [comment]
Also, can you confirm that you followed the guidance in https://github.com/microsoft/gctoolkit#prerequisite-for-building-gctookit ? I'd like to know if there is a problem in the doc. Thanks.

**Comment by anantk24** [comment]
Go through following steps check this resolve your issue:
- ~/.m2/settings.xml - check if this file is present or not. if not present copy from maven/conf folder to .m2 -- this is default setting for IDE
- [create github token](https://github.com/settings/tokens)
- Make sure it has appropriate [scopes](https://github.com/microsoft/gctoolkit/discussions/29) defined. 
- once token is created copy it.
- Edit settings.xml and put server tags for github , enter username, enter token which you created . Refer [here]( https://github.com/microsoft/gctoolkit#prerequisite-for-building-gctookit) for details

**Comment by karianna** [comment]
@andotorg Can you confirm that this is resolved for you?

**Comment by andotorg** [comment]
i create github token， I've specified settings.xml
I downloaded the dependent project again and installed the dependent project locally。
This project is another project that relies on your open source

**Comment by andotorg** [comment]
> https://github.com/microsoft/gctoolkit#prerequisite-for-building-gctokit 中

I followed the instructions in the document, but the document still didn't feel very clear

**Comment by andotorg** [comment]
dependent   https://github.com/microsoft/gctoolkit-testdata

**Comment by karianna** [comment]
I think it's fair to say that the README.md doesn't quite guide the user to the appropriate CONTRIBUTING.md file.  I think the https://github.com/microsoft/gctoolkit#maven-coordinates could also do with a little bit of context (in that those maven coordinates need to be added to any client application that you might create).

**Comment by karianna** [comment]
https://github.com/microsoft/gctoolkit/pull/59 to improve this.
