### ISSUE TITLE
Gctoolkit doesnt parse this log

### ISSUE THREAD

**Issue by logesh056** [microsoft/gctoolkit#301]
https://drive.google.com/file/d/1ZvmgAa0vzXzOEb6LqFDDGvP9mYIDECyF/view?usp=drive_link

_Originally posted by @logesh056 in https://github.com/microsoft/gctoolkit/discussions/299_

**Comment by logesh056** [comment]
**gclogs/unified/g1gc/minimal.log** This log also has the same issue.

**Comment by logesh056** [comment]
hi team, I will solve the issue if you give some details about the parsing rules. shall we have discussion?

**Comment by karianna** [comment]
@kcpeppe and @dsgrieve are much better placed than I to give guidance on the parser :-)

**Comment by logesh056** [comment]
hi @dsgrieve  can you explain some doubts about parsing rules? shall we discuss this in any chat?

**Comment by dsgrieve** [comment]
Minimum flag is `-Xlog:gc*`. It looks like this log was from `-Xlog:gc`
