### ISSUE TITLE
UnifiedG1GCParser doesn't recognize  survivor & eden occupancy

### ISSUE THREAD

**Issue by loyispa** [microsoft/gctoolkit#307]
**Describe the solution you'd like**
Hello, i noticed that the [code](https://github.com/microsoft/gctoolkit/blob/4966123d2fec373c0b67b2d16416014d29eb09ed/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedG1GCParser.java#L298) was already implemented but commented out, is there any special reason for doing this?

**Comment by kcpeppe** [comment]
Good question, I don't know the answer. I'd suggest that the code be uncommented and see if it passes all the tests.

**Comment by loyispa** [comment]
@kcpeppe  I uncommented the code , and all tests passed.  Should i submit a PR or wait for the community to fix it?

**Comment by kcpeppe** [comment]
I'm happy with a pull requsst
