### ISSUE TITLE
new release request

### ISSUE THREAD

**Issue by loyispa** [microsoft/gctoolkit#327]
There have been many commits since the last release, do you have plan to publish a new version ?  Thanks :)

**Comment by karianna** [comment]
@kcpeppe has one more major PR to put in and then I think it would be a good time to do so :-)

**Comment by loyispa** [comment]
Hello, is there any progress? :)

**Comment by karianna** [comment]
https://github.com/microsoft/gctoolkit/pull/331 is what we need to land - almost there!

**Comment by karianna** [comment]
@loyispa - we're still working on this with a new signing service before we can stage on Maven Central, thanks for your patience, I'll update again when we have a concrete date.

**Comment by loyispa** [comment]
Hello, please let me know when it is released :)

**Comment by kcpeppe** [comment]
@loyispa, I will joyfully let everyone know as soon as we've cracked the new signing process. I'm hoping we can get through those in the next couple of days.

**Comment by dsgrieve** [comment]
Just and update. There is a new process we have to follow for signing and publishing to Sonatype and we are dependent on our devops team to implement that process. They are aware of the need, but there are other more critical priorities.

**Comment by fthevenet** [comment]
> Just and update. There is a new process we have to follow for signing and publishing to Sonatype and we are dependent on our devops team to implement that process. They are aware of the need, but there are other more critical priorities.

Thanks for the update. Looking forward to a new release.

**Comment by fthevenet** [comment]
Also, I suspect the same signing issue will need the be resolved first, but once this is the case, are you considering pushing snapshots to maven central's snapshots repo as well as releases? 
Thanks.

**Comment by fthevenet** [comment]
Hi,

Release 3.0.5 has been release 10 days ago but it is still not showing on Maven Central.
Do you have an ETA for this?

Thanks.

**Comment by dsgrieve** [comment]
> Hi,
> 
> Release 3.0.5 has been released 10 days ago but it is still not showing on Maven Central. Do you have an ETA for this?
> 
> Thanks.

Monday, 2024/12/09. 

There were some configuration issues which were resolved this morning. My latest attempt to publish to Maven Central was thwarted by missing javadoc jars and I'm working to resolve that now. This will require a bump in the version number.

**Comment by fthevenet** [comment]
That's great, thanks a lot!

**Comment by dsgrieve** [comment]
Alrighty then. We're anxiously awaiting the arrival of 3.1.2 on Maven Central. "What happened to 3.0.5 and everything in between", you ask? Let's just say they were lost in the confusion.

**Comment by fthevenet** [comment]
Thanks @dsgrieve !

**Comment by dsgrieve** [comment]
https://mvnrepository.com/artifact/com.microsoft.gctoolkit/gctoolkit-api/3.1.2
