### ISSUE TITLE
Create a 'contributor' profile 

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#35]
Create a profile that can be used by a contributor to run tests and checks.  This would make it easy for someone who just wants to fork and build but not contribute. The default profile would not run tests or checks. 

One of the biggest benefits of this is that we could avoid having to download the gclog test data for a casual user. The default profile would set skipTests and skipUnpack to true. The contributor profile would set these to false.

**Comment by karianna** [comment]
Thinking out loud - longer-term we could reduce the test data to only what we need for unit testing and have the full set for integration testing in CI/CD (or optional profile) only?

**Comment by anantk24** [comment]
Agree with @dsgrieve , by this we can avoid setting up github PAT in settings.xml correct?

**Comment by anantk24** [comment]
I will take up this task . Please assign it to me!
