### ISSUE TITLE
Define Checkstyle and PMD rules

### ISSUE THREAD

**Issue by karianna** [microsoft/gctoolkit#36]
> Above changes will not break in github workflow. But we add following commands in workflow, this will fail workflow, we might to have correct error first.
> 
> * mvn checkstyle:check
>   Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default-cli) on project api: You have 2838 Checkstyle violations
> * mvn spotbugs:check
>   Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.3.0:check (default-cli) on project api: failed with 81 bugs and 0 errors

Ah I see - so we need to define the project stds for checkstyle and PMD! :-)

_Originally posted by @karianna in https://github.com/microsoft/gctoolkit/issues/33#issuecomment-897158855_

**Comment by karianna** [comment]
Ii think the core committers should have the initial say here - but worth defining!

**Comment by dsgrieve** [comment]
We should probably center on Google's style since it is IDE neutral, is actively maintained, and there are [reformatting tools](https://github.com/google/google-java-format) available.

**Comment by kirk-microsoft** [comment]
completed
