### ISSUE TITLE
Make DateTimeStamp implement Comparable

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#38]
The use-case is that of a being able to order by date/time a collection of data items extracted from a GC event. DateTimeStamp does have API that allow it to be compared in various ways, but it does not implement Comparable. This makes it difficult to create a sortable, abstract data set (for example DataSet<X extends Comparable<X>, Y extends Comparable<Y>)  that can use DateTimeStamp.

**Comment by anantk24** [comment]
Please Assign this to me . Added [pull request](https://github.com/microsoft/gctoolkit/pull/39) for the same . Thanks :)

**Comment by anantk24** [comment]
Pull request merged. We can close this issue!
