### ISSUE TITLE
DateTimeStamp API that takes double as an arg should handle NaN 

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#49]
Double.NaN should be treated as 0.0.

I would expect, for example, that `new DateTimeStamp(0.0).add(Double.NaN).equals(new DateTimeStamp(0.0))` to be true.

**Comment by anantk24** [comment]
I will take this up . Assign it to me.

**Comment by anantk24** [comment]
Added pull request #50
