### ISSUE TITLE
GCToolkit instantiates JavaVirtualMachine class too soon in the opening workflow

### ISSUE THREAD

**Issue by kirk-microsoft** [microsoft/gctoolkit#6]
GCToolkit should delay creating the JavaVirtualMachine class until after the gc log has been diarized. Delaying will allow GCToolkit to create a specialization of JavaVirtualMachine thus eliminating the need for DefaultJavaVirualMachine

**Comment by Mum2541** [comment]
Duplicate of #

**Comment by pliakas** [comment]
I can work in this bug, if no-one is working. Please assign it to me.

**Comment by dsgrieve** [comment]
@pliakas, Please reach out to @kirk-microsoft, who has specific ideas on this issue.

**Comment by kirk-microsoft** [comment]
Initial refactoring will not support a final refactoring to use an SPI

**Comment by Mum2541** [comment]
#74

**Comment by Mum2541** [comment]
#73

**Comment by Mum2541** [comment]
#6
