### ISSUE TITLE
Rethink GCToolKit API flow: GCAnalyzer returns GCAnalysis

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#73]
For discussion: 
---
Bruno and I had a discussion about this API in general. It was very refreshing to have his un-initiated perspective here. One of the ideas he tossed into the ring was having an 'analyzer' API, to which my response was that is what GCToolkit is. 

Later, I got to thinking about it and I see where he's coming from. I think, perhaps, we should rename the GCToolKit class to `GCAnalyzer`, and have the `analyze` method return a `GCAnalysis` which would be what JavaVirtualMachine is now. I think this would make it more clear to the user what to do and what to use. 

Thoughts?

_Originally posted by @dsgrieve in https://github.com/microsoft/gctoolkit/pull/70#issuecomment-910364145_

**Comment by brunoborges** [comment]
This is also related to #6.

// @kcpeppe @karianna

**Comment by karianna** [comment]
I agree that the name of JavaVirtualMachine could be improved to more accurately represent what it is (which is really the GC information for that JVM as pulled out of the log).  I'm not 100% sure it's a full analysis though, more of a model?

**Comment by brunoborges** [comment]
@kcpeppe you mentioned the following:

> It sounds good but we’re not offering a GC analysis.

And that is correct. Perhaps the method `analyze(dataSource)` shouldn't be called that. It should be called `aggregate` then?

**Comment by kirk-microsoft** [comment]
completed with refactoring
