### ISSUE TITLE
Cleanup POM files for publication

### ISSUE THREAD

**Issue by kcpeppe** [microsoft/gctoolkit#81]
Using [PomChecker](https://kordamp.org/pomchecker/pomchecker-maven-plugin/index.html) to verify the structure of a POM file, yields the following outputs:

for GCToolkit's root POM file
```
[ERROR] The POM file
[ERROR] /Users/kirk/Projects/github/gctoolkit/pom.xml
[ERROR] cannot be uploaded to Maven Central due to the following reasons:
[ERROR]  * <version> can not be -SNAPSHOT.
[ERROR]  * The <repositories> block should not be present.
```

Related to #80 

For GCToolkit/core/api POM file

```
[WARNING] <name> is not defined in POM. Will use value from parent: 
        GCToolKit
[WARNING] <description> is not defined in POM. Will use value from parent: 
        GC log parsing utilities
[WARNING] <url> is not defined in POM. Will use computed value from parent: 
        https://github.com/Microsoft/gctoolkit/core/api
```

Decide which values for `<name>`, `<description>`, `<url>` should be use for child projects.

**Comment by dsgrieve** [comment]
The first one goes away when you do the mvn release:prepare/perform steps.

**Comment by brunoborges** [comment]
I'd suggest talking to @JonathanGiles from the Azure SDK Team on details of their release process to Maven Central.

**Comment by karianna** [comment]
Name can be the same as the parent + ` API`
Description, feel free to come up with a one liner!
URL can be the same as the parent URL

Thanks!

**Comment by anantk24** [comment]
#102 Added pull request please review.
Thanks!

**Comment by anantk24** [comment]
Thanks for @brunoborges  too !
