### ISSUE TITLE
Clarify and configure merge strategy for main branch

### ISSUE THREAD

**Issue by marchof** [microsoft/gctoolkit#87]
The main branch is the one with the history which is kept "forever". Therefore I recommend having a clean and readable history. Currently the default configuration for this repository seems to be "merge" for PRs. This results in additional (useless) merge commits for every PR:

![image](https://user-images.githubusercontent.com/1936262/132119908-07fa78ec-5a8d-4b04-9fbc-6eb12275a2af.png)

I recommend to allow and configure "rebase and merge" only for the main branch, which gives a nice linear history. See for example: https://github.com/jacoco/jacoco/commits/master

![image](https://user-images.githubusercontent.com/1936262/132119974-0ac08b69-498c-4570-944b-70376c09a437.png)

To enforce this you can check "Require linear history" for main in the "Braches" configuration.

**Comment by karianna** [comment]
I've applied the config you suggested, let's see how it plays out :-)
