### ISSUE TITLE
ParallelJVMConfigurationTest is failing

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#89]
```
[INFO] Running com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.675 s <<< FAILURE! - in com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest
[ERROR] com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest.testForDetailsTenuring  Time elapsed: 1.136 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: ps/details/tenuring/p_app_02_gc.log.zip, calculated: false, expected: true ==> expected: <true> but was: <false>
        at gctoolkit.parser.test@2.0.1-SNAPSHOT/com.microsoft.gctoolkit.parser.test.diary.ParallelJVMConfigurationTest.testForDetailsTenuring(ParallelJVMConfigurationTest.java:37)
```

**Comment by anantk24** [comment]
@brunoborges . It is passing on my local machine. Any specific settings needed ?
I am using `mvn -Pcontributor test ` to run testcases under parser module.

**Comment by brunoborges** [comment]
What JDK are you using?

**Comment by anantk24** [comment]
Oracle JDK 11
java -version output
`java version "11.0.7" 2020-04-14 LTS 
JAVA(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)  
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)`

**Comment by dsgrieve** [comment]
Also fails on my local build.

**Comment by karianna** [comment]
> Also fails on my local build.

If it fails why did we close this issue? :-)

**Comment by dsgrieve** [comment]
> If it fails why did we close this issue? :-)

@karianna Because github's UI combines comment and close on the same widget, and puts 'close' where UI's (generally) put the 'Okay' button. Has absolutely nothing to do with a lazy user who clicks without thinking.

**Comment by brunoborges** [comment]
This issue is due to PR #90

**Comment by kirk-microsoft** [comment]
all tests are passing. I believe this maybe due to issues with how the data is currently being imported into the dev environment
