### ISSUE TITLE
test -Pcontributor does not work anymore

### ISSUE THREAD

**Issue by kabutz** [microsoft/gctoolkit#98]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:unpack (download-test-logs) on project gctoolkit: Unable to find/resolve artifact.: com.microsoft.gctoolkit:gctoolkit-gclogs:zip:1.0.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by karianna** [comment]
#90 To resolve this
